version: '3.8'

services:
  nubes3:
    build: ./
    ports:
      - 80:6160
    restart: always
    depends_on:
      - arango
      - seaweedfs-master
      - seaweedfs-volume
    networks:
      - nw_nubes3
  seaweedfs-master:
    image: chrislusf/seaweedfs
    command: 'master -ip=seaweedfs-master -mdir="/mdata"'
    volumes:
      - seaweedfs_mdata:/mdata
    networks:
      - nw_nubes3
  seaweedfs-filer:
    image: chrislusf/seaweedfs # use a remote image
    command: 'filer -master="seaweedfs-master:9333"'
    depends_on:
      - seaweedfs-master
      - seaweedfs-volume
    networks:
      - nw_nubes3
  nats-streaming:
    image: nats-streaming
    command:
      - "--cluster_id"
      - "nats-streaming"
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
#  cronjob:
#    image: chrislusf/seaweedfs # use a remote image
#    command: 'cronjob'
#    environment:
#      # Run re-replication every 5 minutes
#      CRON_SCHEDULE: '*/5 * * * * *' # Default: '*/5 * * * * *'
#      WEED_MASTER: seaweedfs-master:9333 # Default: localhost:9333
#    depends_on:
#      - seaweedfs-master
#      - seaweedfs-volume
#    networks:
#      - nw_nubes3

networks:
  nw_nubes3: { }
volumes:
  seaweedfs_data:
  seaweedfs_mdata:
  arangodb_data_container:
  arangodb_apps_data_container: